In [1]:
import numpy as np
#np.random.seed(None)

from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten, Input
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder




Using TensorFlow backend.


In [0]:
docs = ['kral bir adamdir',
'kral ile kralice evlenir',
'kralice ile kral evlenir',
'biraz gereksiz sozler',
'kralice bir kadindir']



In [7]:
vocab_size = 50
oh = np.array(one_hot("kral kralice adamdir kadindir sozler", vocab_size)).reshape(-1,1)
oh

array([[ 1],
       [48],
       [10],
       [37],
       [11]])

In [8]:
enc = OneHotEncoder()
enc.fit(np.array(range(50)).reshape(-1,1))
oh_enc = enc.transform(oh).toarray()
oh_enc

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 

In [9]:
encoded_docs = [one_hot(kelime,vocab_size) for kelime in docs]
encoded_docs

[[1, 40, 10], [1, 7, 48, 2], [48, 7, 1, 2], [28, 9, 11], [48, 40, 37]]

In [11]:
max_length = 24
padded_docs = pad_sequences(encoded_docs, maxlen = max_length, padding = "post")
padded_docs

array([[ 1, 40, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  7, 48,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [48,  7,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [28,  9, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [48, 40, 37,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [13]:
tuples = np.empty((0,2))

for cumle in padded_docs:
  length = len(cumle)
  for i in range(length):
    if cumle[i] != 0:
      if i<length-1 & cumle[i+1] != 0:
        tuples = np.append(tuples, [[cumle[i], cumle[i+1]]], axis = 0)
        if i<length-2 & cumle[i+2] != 0:
          tuples = np.append(tuples, [[cumle[i], cumle[i+2]]], axis = 0)
      
      if i>0:
        tuples = np.append(tuples, [[cumle[i], cumle[i-1]]], axis = 0)  
        
        if i>1:
          tuples = np.append(tuples, [[cumle[i], cumle[i-2]]], axis = 0)  
          

print(tuples.shape)          
tuples
          

(29, 2)


array([[40., 10.],
       [40.,  1.],
       [10., 40.],
       [10.,  1.],
       [ 1.,  7.],
       [ 1., 48.],
       [ 7., 48.],
       [ 7.,  2.],
       [ 7.,  1.],
       [48.,  7.],
       [48.,  1.],
       [ 2., 48.],
       [ 2.,  7.],
       [48.,  7.],
       [ 7., 48.],
       [ 1.,  7.],
       [ 1., 48.],
       [ 2.,  1.],
       [ 2.,  7.],
       [28.,  9.],
       [28., 11.],
       [ 9., 11.],
       [ 9., 28.],
       [11.,  9.],
       [11., 28.],
       [40., 37.],
       [40., 48.],
       [37., 40.],
       [37., 48.]])

In [15]:
onehotlabels_x = enc.transform(tuples[:,0].reshape(-1,1)).toarray()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.

In [0]:
onehotlabels_y = enc.transform(tuples[:,1].reshape(-1,1)).toarray()


In [17]:
print(onehotlabels_y.shape)

(29, 50)


In [27]:
from keras.layers import Input
model = Sequential()

#model.add(Input(shape = (50)))

bottleneck = Dense(2, activation = "relu", input_shape= (50,))

model.add(bottleneck)
model.add(Dense(50, activation = "softmax"))


model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics=["acc"])

model.summary()




_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 102       
_________________________________________________________________
dense_5 (Dense)              (None, 50)                150       
Total params: 252
Trainable params: 252
Non-trainable params: 0
_________________________________________________________________


In [0]:
hist= model.fit(onehotlabels_x,onehotlabels_y, epochs = 1000, verbose = 0)

In [35]:
for key in hist.history.keys():
  print(key)
  print(hist.history[key])

loss
[0.0909116193652153, 0.09083612263202667, 0.09075967222452164, 0.0906822606921196, 0.09060433506965637, 0.09052592515945435, 0.09044709801673889, 0.0903678759932518, 0.09028829634189606, 0.09020835906267166, 0.0901280865073204, 0.09004749357700348, 0.08996658772230148, 0.08988537639379501, 0.08980388939380646, 0.08972211182117462, 0.0896400511264801, 0.08955772966146469, 0.08947513997554779, 0.0893922820687294, 0.08930917084217072, 0.08922582119703293, 0.08914223313331604, 0.08905838429927826, 0.08897431194782257, 0.08888999372720718, 0.08880545198917389, 0.08872068673372269, 0.08863570541143417, 0.08855050057172775, 0.08846507966518402, 0.08837945014238358, 0.08829361200332642, 0.08820755779743195, 0.08812131732702255, 0.08803487569093704, 0.08794824033975601, 0.08786142617464066, 0.08777438849210739, 0.08768720179796219, 0.08759982883930206, 0.08751225471496582, 0.08742452412843704, 0.08733662217855453, 0.08724856376647949, 0.08716032654047012, 0.08707194030284882, 0.08698338270

In [40]:
model = Sequential()
model.add(bottleneck)
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics=["acc"])
test = model.predict(oh_enc)
print(test)
#"kral kralice adamdir kadindir sozler"

[[1.5450847e+00 1.5972571e+00]
 [2.0365965e+00 2.1423731e+00]
 [6.6101551e-05 2.2302895e+00]
 [4.3828258e-01 1.7850003e+00]
 [1.9542186e+00 3.1667787e-01]]
[[ 1]
 [48]
 [10]
 [37]
 [11]]
