## Unsupervised Learning

### Clustering

2 cluster (kümeleme) uygulamasına bakacağız.
1. K-Means
2. Hierarchical Clustering

In [1]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering

In [2]:
features, labels = load_wine(return_X_y=True)

In [3]:
scaler = StandardScaler()
features = scaler.fit_transform(features)

In [4]:
features.shape

(178, 13)

In [5]:
N_CLUSTERS=3 # Tamamı büyük harflerden oluşan değişkenleri sabit kabul edebiliriz.

#### K-Means

In [6]:
kmeans = KMeans(n_clusters=N_CLUSTERS, verbose=1, random_state=0, algorithm="full")

In [7]:
kmeans.fit(features)

Initialization complete
Iteration 0, inertia 2203.5906463626743.
Iteration 1, inertia 1296.070041191551.
Iteration 2, inertia 1281.468896814162.
Iteration 3, inertia 1279.9661527749458.
Converged at iteration 3: strict convergence.
Initialization complete
Iteration 0, inertia 2076.581238366965.
Iteration 1, inertia 1305.932779664509.
Iteration 2, inertia 1283.44055575899.
Iteration 3, inertia 1281.2533740452773.
Iteration 4, inertia 1279.9661527749458.
Converged at iteration 4: strict convergence.
Initialization complete
Iteration 0, inertia 2036.5816702725494.
Iteration 1, inertia 1301.1872355176786.
Iteration 2, inertia 1280.7643147492684.
Iteration 3, inertia 1278.7607763668154.
Converged at iteration 3: strict convergence.
Initialization complete
Iteration 0, inertia 2412.0934407425266.
Iteration 1, inertia 1329.6802648124985.
Iteration 2, inertia 1288.9238718358422.
Iteration 3, inertia 1282.9280954797623.
Iteration 4, inertia 1282.1344447838694.
Iteration 5, inertia 1280.56740197

KMeans(algorithm='full', n_clusters=3, random_state=0, verbose=1)

In [8]:
def print_ratio(samples, n_clusters=N_CLUSTERS):
    """
    Kullandığımız kümeleme algoritmasının çıkardığı bir kümede bulunan sampleları ve toplam küme sayısını
    verdiğimizde, o kümede bulunan tahmin dağılımını çıkaran bir fonksiyon.
    
    samples: Etiketi 'l' olan 
    """
    sample_len = len(samples) # Kümedeki eleman sayısı
    
    # Verilen kümenin elemanlarının tahmin dağılımını inceliyoruz.
    sample_ratios = {i:(len(samples[samples==i]) / sample_len) for i in range(n_clusters)}
    
    for key, value in sample_ratios.items():
        print(f"Ratio of group {key}: {value:.2f}")

In [9]:
kmeans_preds = kmeans.predict(features)

In [10]:
labels # Gerçek etiketler

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [11]:
kmeans_preds # Tahmini kümeler

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [12]:
kmeans_preds == 0 # 1 olarak tahmin edilen samplelar

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,

In [13]:
labels[kmeans_preds == 0] # 1 olarak tahmin edilen sampleların gerçek etiketi

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

In [14]:
print("K-Means\n")
for i in range(N_CLUSTERS): # Her bir küme için
    print(f"For Group {i}") # i olarak kümelendirdiklerimiz için:
    group_i = labels[kmeans_preds == i] # group_i = i olarak kümelendirilen sampleların gerçek etiketi
    print_ratio(group_i) # Gerçek etiketlerin dağılımı
    print("----")

K-Means

For Group 0
Ratio of group 0: 0.00
Ratio of group 1: 0.06
Ratio of group 2: 0.94
----
For Group 1
Ratio of group 0: 0.00
Ratio of group 1: 1.00
Ratio of group 2: 0.00
----
For Group 2
Ratio of group 0: 0.97
Ratio of group 1: 0.03
Ratio of group 2: 0.00
----


#### Hierarchical Clustering

In [15]:
# Farklı uzaklık metrikleri ve küme belirleme yöntemi kullanan 3 kümeleme modeli tanımlıyoruz

hi_cl_euclidean = AgglomerativeClustering(n_clusters=N_CLUSTERS, affinity="euclidean", linkage="average")
hi_cl_cos = AgglomerativeClustering(n_clusters=N_CLUSTERS, affinity="cosine", linkage="average")
hi_def = AgglomerativeClustering(n_clusters=N_CLUSTERS)

In [16]:
euc_preds = hi_cl_euclidean.fit_predict(features)
cos_preds = hi_cl_cos.fit_predict(features)
def_preds = hi_def.fit_predict(features)

In [17]:
print("Euclidean Distance\n")
for i in range(N_CLUSTERS):
    print(f"For Group {i}")
    group_i = labels[euc_preds == i]
    print_ratio(group_i)
    print("----")

Euclidean Distance

For Group 0
Ratio of group 0: 0.33
Ratio of group 1: 0.39
Ratio of group 2: 0.28
----
For Group 1
Ratio of group 0: 0.00
Ratio of group 1: 1.00
Ratio of group 2: 0.00
----
For Group 2
Ratio of group 0: 0.33
Ratio of group 1: 0.67
Ratio of group 2: 0.00
----


In [18]:
print("Cosine Distance\n")
for i in range(N_CLUSTERS):
    print(f"For Group {i}")
    group_i = labels[cos_preds == i]
    print_ratio(group_i)
    print("----")

Cosine Distance

For Group 0
Ratio of group 0: 0.87
Ratio of group 1: 0.13
Ratio of group 2: 0.00
----
For Group 1
Ratio of group 0: 0.00
Ratio of group 1: 1.00
Ratio of group 2: 0.00
----
For Group 2
Ratio of group 0: 0.00
Ratio of group 1: 0.08
Ratio of group 2: 0.92
----


In [19]:
print("Default Arguments\n")
for i in range(N_CLUSTERS):
    print(f"For Group {i}")
    group_i = labels[def_preds == i]
    print_ratio(group_i)
    print("----")

Default Arguments

For Group 0
Ratio of group 0: 0.00
Ratio of group 1: 1.00
Ratio of group 2: 0.00
----
For Group 1
Ratio of group 0: 0.00
Ratio of group 1: 0.14
Ratio of group 2: 0.86
----
For Group 2
Ratio of group 0: 0.92
Ratio of group 1: 0.08
Ratio of group 2: 0.00
----


## Supervised Learning

Gözetimli öğrenme için de Naive Bayes uygulamasına bakacağız.

### Naive Bayes

In [20]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords
from nltk import RegexpTokenizer
from string import punctuation
from nltk.stem.porter import *

from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [21]:
punctuation = set(list(punctuation)) # Noktalama işaretleri

In [22]:
data = pd.read_csv("spam_or_not_spam.csv")

In [23]:
features = data.email
labels = data.label

In [24]:
features = features.str.lower() # Karakterleri küçük harfe çeviriyoruz

In [25]:
features = features.str.split() # Cümle halindeki stringleri listeye çeviriyoruz.
# Örneğin "Ugur Ali Kaplan" -> ["Ugur", "Ali", "Kaplan"]

In [26]:
features.isna().sum() # Boş olan bir değer

1

In [27]:
# Boş olan değeri çıkarıyoruz
labels = labels[~features.isna()]
features = features[~features.isna()]

In [28]:
# İngilizcede yaygın stopwordleri indiriyoruz. Mesela I, we, have, had. Bunların bize çok faydası yok.
nltk.download("stopwords")
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ugurkap/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [29]:
# Stopword olmayanları tutuyoruz, stop wordleri listeden çıkarıyoruz.
features = features.apply(lambda word_tokens: [w for w in word_tokens if not w in stop_words.union(punctuation)])

In [30]:
# Kelime köklerini elde etmek için PorterStemmer kullanacağız.
stemmer = PorterStemmer()

In [31]:
# Her kelimenin kökünü alıyoruz.
features = features.apply(lambda word_tokens: [stemmer.stem(w) for w in word_tokens])

In [32]:
X_tr, X_te, y_tr, y_te = train_test_split(features, labels, test_size=0.1, random_state=0)

In [33]:
assert (X_tr.index == y_tr.index).all()

In [34]:
assert (X_te.index == y_te.index).all()

In [35]:
# Bag-of-Words
vectorizer = CountVectorizer(tokenizer=lambda x: x, preprocessor=lambda y: y, max_features=10000)

In [36]:
X_tr = vectorizer.fit_transform(X_tr)

In [37]:
X_te = vectorizer.transform(X_te)

In [38]:
X_tr = X_tr.toarray()
X_te = X_te.toarray()

In [39]:
X_tr.shape

(2699, 10000)

In [40]:
X_te.shape

(300, 10000)

In [41]:
X_tr[0]

array([0, 0, 0, ..., 0, 0, 0])

Artık sınıflandırımızı tanımlayabiliriz.

In [42]:
# Gaussian Naive Bayes
clf = GaussianNB()

In [43]:
clf.fit(X_tr, y_tr)

GaussianNB()

In [44]:
train_preds = clf.predict(X_tr)

In [45]:
test_preds = clf.predict(X_te)

In [46]:
print(classification_report(y_tr, train_preds))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      2247
           1       0.83      1.00      0.91       452

    accuracy                           0.97      2699
   macro avg       0.92      0.98      0.94      2699
weighted avg       0.97      0.97      0.97      2699



In [47]:
print(classification_report(y_te, test_preds))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       253
           1       0.75      0.85      0.80        47

    accuracy                           0.93       300
   macro avg       0.86      0.90      0.88       300
weighted avg       0.94      0.93      0.93       300



In [48]:
multi_clf = MultinomialNB() # Multinomial Naive Bayes

In [49]:
multi_clf.fit(X_tr, y_tr)

MultinomialNB()

In [50]:
multi_train_preds = multi_clf.predict(X_tr)
multi_test_preds = multi_clf.predict(X_te)

In [51]:
print(classification_report(y_tr, multi_train_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2247
           1       0.98      0.98      0.98       452

    accuracy                           0.99      2699
   macro avg       0.99      0.99      0.99      2699
weighted avg       0.99      0.99      0.99      2699



In [52]:
print(classification_report(y_te, multi_test_preds))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       253
           1       1.00      0.94      0.97        47

    accuracy                           0.99       300
   macro avg       0.99      0.97      0.98       300
weighted avg       0.99      0.99      0.99       300



In [53]:
def classify_text(inp, clf=multi_clf):
    """
    Yukarıda yaptığımız veri işleme adımlarını tek fonksiyon içine topladık. Verilen sınıflandırıcıya göre
    Spam veya Not Spam şeklinde çıktı veriyoruz.
    """
    def process_text(text):
        word_tokens = text.lower().split()
        word_tokens = [w for w in word_tokens if not w in stop_words.union(punctuation)]
        word_tokens = [stemmer.stem(w) for w in word_tokens]
        return vectorizer.transform(np.array([word_tokens])).toarray()
    
    print("Spam" if clf.predict(process_text(inp))[0] == 1 else "Not Spam")

In [54]:
spam_example = "I am very rich but I do not have access to my wallet. If you send money to my account, I will return it 10 times more. Pls help."

In [55]:
ham_example = "See you at the meeting. - Your boss"

In [56]:
classify_text(spam_example)

Spam


In [57]:
classify_text(ham_example)

Not Spam


Good.

#### Comparing with Others

Examples are taken from https://www.kaggle.com/bendith/naive-bayes-spam-classifier#Fitting-model-and-getting-result

They also use Naive Bayes. Their model report "Spam, Not Spam, Spam".

Ground Truth: "Spam, Not Spam, Not Spam"

In [58]:
example_mail_1 = "Hi, My name is Warren E. Buffett an American business magnate, investor and philanthropist. am the most successful investor in the world. I believe strongly in‘giving while living’ I had one idea that never changed in my mind? that you should use your wealth to help people and i have decided to give {$1,500,000.00} One Million Five Hundred Thousand United Dollars, to randomly selected individuals worldwide. On receipt of this email, you should count yourself as the lucky individual. Your email address was chosen online while searching at random. Kindly get back to me at your earliest convenience before i travel to japan for my treatment , so I know your email address is valid. Thank you for accepting our offer, we are indeed grateful You Can Google my name for more information: God bless you. Best Regard Mr.Warren E. Buffett Billionaire investor !"
example_mail_2 = "Hi guys I want to build a website like REDACTED and I wanted to get your perspective of whether that site is good from the users' perspective before I go ahead and build something similar. I think that the design of the site is very modern and nice but I am not sure how people would react to a similar site? I look forward to your feedback. Many thanks! "
example_mail_3 = "As a result of your application for the position of Data Engineer, I would like to invite you to attend an interview on May 30, at 9 a.m. at our office in Washington, DC. You will have an interview with the department manager, Moris Peterson. The interview will last about 45 minutes. If the date or time of the interview is inconvenient, please contact me by phone or email to arrange another appointment. We look forward to seeing you. "

In [59]:
classify_text(example_mail_1)

Spam


In [60]:
classify_text(example_mail_2)

Not Spam


In [61]:
classify_text(example_mail_3)

Not Spam
